name: ðŸŽ‰ Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:  # å…è®¸æ‰‹åŠ¨è§¦å‘ï¼Œå¹¶å¯ä»¥æŒ‡å®šåˆ†æ”¯
    inputs:
      branch:
        description: 'Branch to release from'
        required: true
        default: 'main'  # é»˜è®¤ä½¿ç”¨ main åˆ†æ”¯
        type: string
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - name: Set node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: pnpm

      - run: npx changelogithub
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{secrets.GH_TOKEN}}

      - name: Install
        run: pnpm install --no-frozen-lockfile

      # è¿è¡Œ build æŒ‡ä»¤
      - name: Run build preset
        run: pnpm run build:docs:preset

      - name: Build
        run: pnpm run build

      - name: Set Timezone
        run: |
          sudo ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
          echo "Asia/Shanghai" | sudo tee /etc/timezone
          date
        shell: bash

      - name: Set npmrc for all packages
        run: |
          for package in $(find dist/* -maxdepth 0 -type d); do
            echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ${package}/.npmrc
          done
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Set npmrc for root packages
        run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > dist/.npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish to npm
        run: pnpm run publish:script
